# App store metadata; see https://appfair.net/#App.yml
app:
  primary_category: "UTILITIES"
  secondary_category: "PRODUCTIVITY"
  privacy_url: "https://appfair.net/privacy"
  # subtitle: "A really great App Fair app"
  # promotional_text: "Be the first to download this app!"
  # description: "A simple app fair app."
  # keywords: "appfair"
  # locales: # keys like "fr-FR" can contain localized description, name, etc.

# Pages / Jekyll configuration::
remote_theme: appfair/fairapp-theme

